name: Test interfaces/expatistan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test interafaces/expatistan.py
        run: |
          python -m unittest tests.test_expatistan